# Basic Numpy

In [1]:
import numpy as np

In [2]:
pl = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
pl

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
type(pl)

list

In [5]:
na = np.array(pl)
na

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
type(na)

numpy.ndarray

In [7]:
pl[0] = 9001
na

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
type(pl[0]), type(na[0])

(int, numpy.int32)

In [10]:
na[0:3]

array([0, 1, 2])

In [11]:
na[:3]

array([0, 1, 2])

In [12]:
na[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
na[::2]

array([0, 2, 4, 6, 8])

In [15]:
na[::-2]

array([9, 7, 5, 3, 1])

In [16]:
na[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [18]:
na[:3] = 9001
na

array([9001, 9001, 9001,    3,    4,    5,    6,    7,    8,    9])

In [19]:
na[:3] = na[5:8]
na

array([5, 6, 7, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.empty(10)

array([8.72325920e-312, 1.77863633e-322, 0.00000000e+000, 0.00000000e+000,
       2.33419537e-312, 1.08672380e-071, 1.38054166e-047, 5.20267661e-090,
       4.95688749e-062, 4.57625918e-315])

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros(10, dtype = np.int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [25]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
np.ones_like(na)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [28]:
na.astype(np.complex128)

array([5.+0.j, 6.+0.j, 7.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j,
       8.+0.j, 9.+0.j])

In [29]:
len(na)

10

In [30]:
na.size

10

In [31]:
na.shape

(10,)

In [47]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
y = np.array([00, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [34]:
x * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [35]:
x + 7

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [36]:
x / 7

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429])

In [37]:
x * y

array([  0,  10,  40,  90, 160, 250, 360, 490, 640, 810])

In [38]:
x.dot(y)

2850

In [40]:
x > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [48]:
x[x > 4]

array([5, 6, 7, 8, 9])

In [60]:
na = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
])
na

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [61]:
na[0, 0]

0

In [62]:
na[1, 1]

4

In [63]:
na[:, 2]

array([2, 5, 8])

In [66]:
na = np.ones((5, 3))
na

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [67]:
len(na)

5

In [68]:
na.size

15

In [69]:
na.shape

(5, 3)

In [70]:
x = np.ones((5, 5)) * 2
y = np.ones((5, 5)) * 3
x, y

(array([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]),
 array([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]]))

In [71]:
x * y

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [72]:
x.dot(y)

array([[30., 30., 30., 30., 30.],
       [30., 30., 30., 30., 30.],
       [30., 30., 30., 30., 30.],
       [30., 30., 30., 30., 30.],
       [30., 30., 30., 30., 30.]])

In [73]:
x @ y

array([[30., 30., 30., 30., 30.],
       [30., 30., 30., 30., 30.],
       [30., 30., 30., 30., 30.],
       [30., 30., 30., 30., 30.],
       [30., 30., 30., 30., 30.]])

# Cool functions

In [85]:
np.random.randint(0, 10, size = (4, 5))

array([[2, 8, 3, 9, 2],
       [5, 2, 0, 2, 5],
       [1, 3, 1, 8, 3],
       [0, 5, 3, 2, 4]])

In [93]:
np.random.random()

0.29478917600573284

In [94]:
na = np.array([
    [1, 1, 2],
    [1, 1, 5],
    [2, 5, 1]
])
na

array([[1, 1, 2],
       [1, 1, 5],
       [2, 5, 1]])

In [95]:
np.linalg.det(na)

-8.999999999999998

In [96]:
np.linalg.eig(na)

(array([ 6.78425963,  0.32298991, -4.10724954]),
 array([[ 0.34667469,  0.92593267, -0.14988445],
        [ 0.64698789, -0.35174727, -0.6765209 ],
        [ 0.67913425, -0.13755924,  0.7210091 ]]))